# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rbm25_wrappers", use_symbols = TRUE, package_name = "rbm25")

#' @usage NULL
#' @useDynLib rbm25, .registration = TRUE
NULL

build_engine <- function(corpus, language, k1, b) .Call(wrap__build_engine, corpus, language, k1, b)

search <- function(engine, query, max_n) .Call(wrap__search, engine, query, max_n)

#'
#' @section Methods:
#'\subsection{Method `n_docs`}{
#'Count the number of items in the negine
#'}
#'
#'\subsection{Method `get_all_docs`}{
#'Get all documents from the engine
#'}
#'
Engine <- new.env(parent = emptyenv())

Engine$new <- function(corpus, language, k1, b, ids) .Call(wrap__Engine__new, corpus, language, k1, b, ids)

Engine$upsert <- function(id, text) .Call(wrap__Engine__upsert, self, id, text)

Engine$remove <- function(id) .Call(wrap__Engine__remove, self, id)

Engine$get <- function(id) .Call(wrap__Engine__get, self, id)

Engine$search <- function(query, max_n) .Call(wrap__Engine__search, self, query, max_n)

Engine$n_docs <- function() .Call(wrap__Engine__n_docs, self)

Engine$get_all_docs <- function() .Call(wrap__Engine__get_all_docs, self)

#' @export
`$.Engine` <- function (self, name) { func <- Engine[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Engine` <- `$.Engine`


# nolint end
